name = "remix-practice-app"
compatibility_date = "2024-03-12"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "remix-practice-db"
database_id = "384534da-4983-4c10-8eba-8f119241ccff"